[package]
authors = ["Fabien Bellanger <valentil@gmail.com>"]
description = "ESC/POS printer driver"
documentation = "https://docs.rs/escpos"
edition = "2021"
homepage = "https://github.com/fabienbellanger/escpos-rs"
keywords = ["escpos", "printer", "driver", "pos", "usb"]
license = "MIT"
name = "escpos"
readme = "README.md"
repository = "https://github.com/fabienbellanger/escpos-rs"
version = "0.2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["barcodes", "2d_codes"]
full = ["barcodes", "qrcode", "graphics"]
barcodes = []
2d_codes = ["qrcode", "gs1_databar"]
qrcode = []
gs1_databar = []
graphics = ["dep:image"]

[dependencies]
encoding_rs = "0.8.33"
image = { version = "0.24.7", optional = true }
log = "0.4.20"

[dev-dependencies]
env_logger = "0.10.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
