[package]
authors = ["Fabien Bellanger <valentil@gmail.com>"]
description = "ESCPOS printer driver for Rust"
edition = "2021"
homepage = "https://github.com/fabienbellanger/escpos-rs"
keywords = ["escpos", "printer", "driver", "thermal", "usb"]
license = "MIT"
name = "escpos"
readme = "README.md"
repository = "https://github.com/fabienbellanger/escpos-rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
barcode = []
full = ["barcode", "qrcode", "graphics"]
graphics = ["dep:image"]
qrcode = []

[dependencies]
encoding_rs = "0.8.33"
image = {version = "0.24.7", optional = true}
log = "0.4.20"
