name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libudev-dev
        run: sudo apt-get install libudev-dev
      - name: Fmt
        run: cargo fmt
      - name: Clippy
        run: cargo clippy --all-features -- -D warnings
      - name: Run tests
        run: cargo test --all-features -- --nocapture
      - name: Build
        run: cargo build --all-features --verbose
