name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fmt
      run: cargo fmt
    - name: Clippy
      run: cargo clippy --all-features -- -D warnings
    - name: Run tests
      run: cargo test --all-features -- --nocapture
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: fabienbellanger/escpos-rs
    - name: Build
      run: cargo build --all-features --verbose
